version: '3'

services:
  db:
    image: mysql:5.7.9
    environment:
      - MYSQL_ROOT_PASSWORD=ranosys
      - MYSQL_USER=anupam
      - MYSQL_PASSWORD=ranosys
      - MYSQL_DATABASE=multi_tenent
      - protocol=tcp
    expose:
        - "3309"
    ports:
      - "3309:3306"

  web:
    build: .
    command: bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db







