# Generated by Django 2.1.4 on 2018-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(default=None, max_length=50)),
                ('subdomain_prefix', models.CharField(default=None, max_length=100, unique=True)),
                ('company_name', models.CharField(default=None, max_length=100)),
                ('company_email', models.EmailField(default=None, max_length=100, unique=True)),
                ('role', models.CharField(choices=[('Product', 'Product'), ('1', ' '), ('Innvation', 'Innvation'), ('Others', 'Others'), ('Risk ', 'Risk'), ('Marketing', 'Marketing')], default='1', max_length=50)),
                ('country_code', models.IntegerField(default=None)),
                ('mobile_no', models.CharField(default=None, max_length=10)),
                ('industry', models.CharField(choices=[('1', ' '), ('Others', 'Others'), ('FinancialService', 'FinancialService'), ('ICO', 'ICO'), ('HealthCare ', 'HealthCare')], default='1', max_length=50)),
                ('website_url', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(default=None, max_length=50)),
                ('additional_info', models.CharField(default=None, max_length=120)),
                ('is_verified', models.BooleanField(default=None)),
                ('test_api_token', models.CharField(blank=True, default=None, max_length=100)),
                ('live_api_token', models.CharField(blank=True, default=None, max_length=100)),
                ('sdk_token', models.CharField(blank=True, default=None, max_length=100)),
                ('contact_person', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
