# Generated by Django 2.1.4 on 2018-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20181212_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='industry',
            field=models.CharField(choices=[(4, 'ICO'), (1, ' '), (5, 'Others'), (2, 'FinancialService'), (3, 'HealthCare')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='role',
            field=models.CharField(choices=[(5, 'Innvation'), (1, ' '), (4, 'Marketing'), (3, 'Risk'), (2, 'Product'), (6, 'Others')], default='1', max_length=50),
        ),
    ]
