# Generated by Django 2.1.4 on 2018-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20181213_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='industry',
            field=models.CharField(choices=[(2, 'FinancialService'), (3, 'HealthCare'), (5, 'Others'), (4, 'ICO'), (1, ' ')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='role',
            field=models.CharField(choices=[(6, 'Others'), (2, 'Product'), (4, 'Marketing'), (3, 'Risk'), (1, ' '), (5, 'Innvation')], default=1, max_length=50),
        ),
    ]
