# Generated by Django 2.1.4 on 2018-12-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_auto_20181213_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='industry',
            field=models.CharField(choices=[('Others', 'Others'), ('FinancialService', 'FinancialService'), ('HealthCare', 'HealthCare'), (1, ' '), ('ICO', 'ICO')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='role',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Risk', 'Risk'), ('Others', 'Others'), ('Product', 'Product'), (1, ' '), ('Innvation', 'Innvation')], default=1, max_length=50),
        ),
    ]
