# Generated by Django 2.1.4 on 2018-12-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_auto_20181213_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='industry',
            field=models.CharField(choices=[('HealthCare', 'HealthCare'), ('ICO', 'ICO'), (1, ' '), ('Others', 'Others'), ('FinancialService', 'FinancialService')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='role',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Risk', 'Risk'), (1, ' '), ('Others', 'Others'), ('Product', 'Product'), ('Innvation', 'Innvation')], default=1, max_length=50),
        ),
    ]
